### ISSUE TITLE
DisplayBPM<->DisplayBMP,  EFIAPI for functions of ScreenshotDriver.c

### ISSUE THREAD

**Issue by timotheuslin** [fpmurphy/UEFI-Utilities-2019#3]
Hi Murphy,

First of all, thank you for sharing these useful UEFI utilities.

I'd like to raise two issues in your UEFI-Utilities-2019:
1. The folder name Display**BPM** is wrong which should be Display**BMP**.
2. The prototypes of some functions in ScreenshotDriver.c are missing "**EFIAPI**". This causes "conflict type" compilation error.

--
Timothy

**Comment by fpmurphy** [comment]
Fixed DisplayBPM issue. Thanks for pointing it out.

Sorry but I do not get any "conflict type" errors in my build environment - Linux, x64, clang.
